# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.10

    working_directory: ~/aibolik.github.io

    branches:
        only:
            - master-v3


    steps:
      - checkout

      - add_ssh_keys:
          fingerprints:
            - "8e:7a:7f:6b:e3:53:fa:84:c0:cf:13:dc:9d:4e:a1:87"

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: 
          name: "Install dependencies"
          command: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      # run tests!
      - run: 
          name: "Run 'imaginary' tests"
          command: yarn test
    
      - run:
          name: "Build Gatsby website"
          command: yarn build

      - run:
          name: "Deploy to GitHub Pages"
          command: yarn deploy


